defaults:
  - _self_
  - task: maniskill/put_on_plate_main
  - override hydra/launcher: submitit_local

# task settings
task_name: ${task.task_name}
frame_stack: ${task.frame_stack}
action_repeat: ${task.action_repeat}
discount: 0.99
# train settings
num_train_frames: ${task.num_train_frames}
num_seed_frames: ${task.num_seed_frames}
# eval
eval_every_frames: ${task.eval_every_frames}
num_eval_episodes: ${task.num_eval_episodes}
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 1
nstep: 3
batch_size: 256
demo_path_prefix: /home/darling/wm_vla/iVideoGPT/mbrl/demonstrations # TODO: make it relative path
demo: false

# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true
max_eval_videos: 3
max_gifs_per_type: 3
# experiment
experiment: exp
exp_name: maniskill_drq
# agent
lr: 1e-4
feature_dim: 50

# maniskill settings
obs_mode: rgb+segmentation
control_mode: ${task.control_mode}
sim_backend: gpu
sim_freq: 500
control_freq: 5
max_episode_steps: ${task.max_episode_steps}
obj_set: ${task.obj_set}
render_mode: rgb_array
shader_pack: default
render_backend: gpu
agent_update_times: 2

stddev_schedule: ${task.stddev_schedule}

agent:
  _target_: drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 1
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  beta: 0.0 # intrinsic bonus
  delay_steps: 1

hydra:
  run:
    dir: ./log_mbrl/${now:%Y.%m.%d}/${exp_name}_${task_name}_${now:%H%M%S}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${exp_name}_${task_name}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
