defaults:
  - _self_
  - task: maniskill/put_on_plate_main
  - override hydra/launcher: submitit_local

name: "0"  # hydra run name (can be overridden with name=foo)
# task settings
task_name: ${task.task_name}
frame_stack: ${task.frame_stack}
action_repeat: ${task.action_repeat}
discount: 0.99
# train settings
num_train_frames: ${task.num_train_frames}
num_seed_frames: ${task.num_seed_frames}
# eval
eval_every_frames: ${task.eval_every_frames}
num_eval_episodes: ${task.num_eval_episodes}
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 1
nstep: 3
batch_size: 256
demo_path_prefix: /home/darling/wm_vla/iVideoGPT/mbrl/demonstrations # TODO: make it relative path
demo: false

# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true
gif_save_every_frames: 30000
max_gifs_per_type: 3
max_eval_videos: 3
# experiment
experiment: exp
exp_name: maniskill_mbpo
# agent
lr: 1e-4
feature_dim: 50

# maniskill settings
obs_mode: rgb+segmentation
control_mode: ${task.control_mode}
sim_backend: gpu
sim_freq: 500
control_freq: 5
max_episode_steps: ${task.max_episode_steps}
obj_set: ${task.obj_set}
render_mode: rgb_array
shader_pack: default
render_backend: gpu
agent_update_times: 2

stddev_schedule: ${task.stddev_schedule}

agent:
  _target_: drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 1
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  beta: 0.0 # intrinsic bonus
  delay_steps: 1

# mbpo
gen_every_steps: 200
gen_batch: 32
gen_horizon: 10
update_gen_every_step: 10
update_tokenizer_every_step: 40
update_gen_times: 1
init_update_gen_steps: 1000
init_gen_times: 20
real_ratio: 0.5
start_mbpo: 4000

world_model:
  load_pretrained_model: true
  config_name: /home/darling/iVideoGPT/configs/llama/config.json
  vqgan_type: ctx_vqgan
  pretrained_model_name_or_path: /home/darling/iVideoGPT/pretrained_models/ivideogpt-oxe-64-act-free/tokenizer
  pretrained_transformer_path: /home/darling/iVideoGPT/pretrained_models/ivideogpt-oxe-64-act-free/transformer
  load_internal_llm: true
  llama_attn_drop: 0.1
  fast_reward_predictor: false
  symlog: true

  context_length: 2
  segment_length: 12
  action_dim: 7

  batch_size: 16
  selected_params: true
  tok_lr: 1e-4
  tok_wd: 0.0
  tok_beta1: 0.9
  tok_beta2: 0.999
  max_grad_norm: 1.0
  max_target_frames: 5

  model_lr: 1e-4
  model_wd: 0.0
  embed_no_wd: true

  reward_lr: 1e-4
  reward_wd: 1e-6
  reward_weight: 1.0

wandb:
  enable: true
  entity: flare-robot
  team: flare-robot
  org: ucd-dare
  project: ${task_name}
  group: ${exp_name}
  mode: online

hydra:
  run:
    dir: ./log_mbrl/${now:%Y.%m.%d}/${exp_name}_${task_name}_${now:%H%M%S}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${exp_name}_${task_name}
    subdir: ${hydra.job.num}
